name: Pull Request Build

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'MultiplayerExtensions.sln'
      - 'MultiplayerExtensions/**'
      - '.github/workflows/PR_Build.yml'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
    - name: Initialize modding environment
      uses: beat-forge/init-beatsaber@v1.6.4
      with:
        token: ${{ github.token }}
        repo: beat-forge/beatsaber-stripped
        manifest: ./MultiplayerExtensions/manifest.json
    - name: Fetch Mod References
      uses: Goobwabber/download-beatmods-deps@1.2
      with:
        manifest: ./MultiplayerExtensions/manifest.json
    - name: Build
      id: Build
      env: 
        FrameworkPathOverride: /usr/lib/mono/4.8-api
      run: dotnet build --configuration Release
    - name: GitStatus
      run: git status
    - name: Echo Filename
      run: echo $BUILDTEXT \($ASSEMBLYNAME\)
      env:
        BUILDTEXT: Filename=${{ steps.Build.outputs.filename }}
        ASSEMBLYNAME: AssemblyName=${{ steps.Build.outputs.assemblyname }}
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.Build.outputs.filename }}
        path: ${{ steps.Build.outputs.artifactpath }}
